### ANY CHANGES TO THIS FILE DOES NOT REQUIRE A RESTART ###
# Each queueManager requires 9 threads to fetch its metrics concurrently and 1 main thread to run the extension.
# So for ex, if there are 2 queueManagers configured, please set the numberOfThreads to be 19 (2*9+1)
numberOfThreads: 20

#This will create it in specific Tier aka Component. Replace <COMPONENT_ID>. Please make sure to have a trailing |.
#To find out the COMPONENT_ID, please see the screen shot here https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
#metricPrefix: "Server|Component:<COMPONENT_ID>|Custom Metrics|WebsphereMQ|"
#For SIM
metricPrefix: "Custom Metrics|WebsphereMQ|"

#This is the timeout on queue metrics and channel metrics threads.Default value is 20 seconds.
#No need to change the default unless you know what you are doing.
#queueMetricsCollectionTimeoutInSeconds: 40
#channelMetricsCollectionTimeoutInSeconds: 40
#topicMetricsCollectionTimeoutInSeconds: 40

#Uncomment only if encryption of passwords is wanted.
#encryptionKey: ""
useIBMCipherMappings: "false"

queueManagers:
  - displayName: ""
    # displayName (optional). This will be your QM name that will show up in AppD metric path.
    host: "localhost"
    port: 1414

    #Actual name of the queue manager
    name: "QM1"

    #The transport type for the queue manager connection, the default is "Bindings" for a binding type connection
    #For bindings type, connection WMQ extension (i.e machine agent) need to be on the same machine on which WebbsphereMQ server is running
    #For client type, connection change it to "Client".
    transportType: "Client"

    #Channel name of the queue manager, channel should be server-conn type.
    #This field is not required in case of transportType: Bindings
    channelName: "DEV.ADMIN.SVRCONN"

    #for user access level, please check "Access Permissions" section on the extensions page
    #comment out the username and password in case of transportType: Bindings.
    username: "admin"
    password: "root"

    #Uncomment only if encryption of passwords is wanted.
    #encryptedPassword: ""

    #PCF requests are always sent to SYSTEM.ADMIN.COMMAND.QUEUE. The PCF responses to these requests are sent to the default reply-to queue called
    #SYSTEM.DEFAULT.MODEL.QUEUE. However, you can override this behavior and send it to a temporary dynamic queue by changing the modelQueueName and replyQueuePrefix fields.
    #For more details around this https://www.ibm.com/support/knowledgecenter/SSFKSJ_7.5.0/com.ibm.mq.ref.adm.doc/q083240_.htm & https://www.ibm.com/support/knowledgecenter/SSFKSJ_8.0.0/com.ibm.mq.adm.doc/q020010_.htm
    modelQueueName: "Q1"
    #replyQueuePrefix: ""


    #Sets the CCSID used in the message descriptor of request and response messages. The default value is MQC.MQCCSI_Q_MGR.
    #To set this, please use the integer value.
    #ccsid:

    #Sets the encoding used in the message descriptor of request and response messages. The default value is MQC.MQENC_NATIVE.
    #To set this, please use the integer value.
    #encoding:

    # IBM Cipher Suite e.g. "SSL_RSA_WITH_AES_128_CBC_SHA256"..
    # For translation to IBM Cipher  http://www.ibm.com/support/knowledgecenter/SSFKSJ_8.0.0/com.ibm.mq.dev.doc/q113210_.htm
    #cipherSuite: ""


    queueFilters:
        #Can provide complete queue name or generic names. A generic name is a character string followed by an asterisk (*),
        #for example ABC*, and it selects all objects having names that start with the selected character string.
        #An asterisk on its own matches all possible names.
        include: ["*"]
        exclude:
             #type value: STARTSWITH, EQUALS, ENDSWITH, CONTAINS
           - type: "STARTSWITH"
             #The name of the queue or queue name pattern as per queue filter, comma separated values
             values: ["SYSTEM","AMQ"]


    channelFilters:
        #Can provide complete channel name or generic names. A generic name is a character string followed by an asterisk (*),
        #for example ABC*, and it selects all objects having names that start with the selected character string.
        #An asterisk on its own matches all possible names.
        include: ["*"]
        exclude:
           #type value: STARTSWITH, EQUALS, ENDSWITH, CONTAINS
           - type: "STARTSWITH"
           #The name of the queue or queue name pattern as per queue filter, comma separated values
             values: ["SYSTEM"]

    listenerFilters:
        #Can provide complete channel name or generic names. A generic name is a character string followed by an asterisk (*),
        #for example ABC*, and it selects all objects having names that start with the selected character string.
        #An asterisk on its own matches all possible names.
        include: ["*"]
        exclude:
           #type value: STARTSWITH, EQUALS, ENDSWITH, CONTAINS
           - type: "STARTSWITH"
           #The name of the queue or queue name pattern as per queue filter, comma separated values
             values: ["SYSTEM"]

    topicFilters:
        # For topics, IBM MQ uses the topic wildcard characters ('#' and '+') and does not treat a trailing asterisk as a wildcard
        # https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_7.5.0/com.ibm.mq.pla.doc/q005020_.htm
        include: ["#"]
        exclude:
             #type value: STARTSWITH, EQUALS, ENDSWITH, CONTAINS
           - type: "STARTSWITH"
             #The name of the queue or queue name pattern as per queue filter, comma separated values
             values: ["SYSTEM","$SYS"]

mqMetrics:
  # This Object will extract queue manager metrics
  - metricsType: "queueMgrMetrics"
    metrics:
      exclude: []
      
  # This Object will extract queue metrics
  - metricsType: "queueMetrics"
    metrics:
      exclude: []

      
  # This Object will extract channel metrics
  - metricsType: "channelMetrics"
    metrics:
      exclude: []


  - metricsType: "listenerMetrics"
    metrics:
      exclude: []

  # This Object will extract topic metrics
  - metricsType: "topicMetrics"
    metrics:
      exclude: []

#Run it as a scheduled task instead of running every minute.
#If you want to run this every minute, comment this out
#taskSchedule:
#  numberOfThreads: 1
#  taskDelaySeconds: 300


sslConnection:
  trustStorePath: ""
  trustStorePassword: ""
  trustStoreEncryptedPassword: ""

  keyStorePath: ""
  keyStorePassword: ""
  keyStoreEncryptedPassword: ""


# If any of the following fields are not set, the values of the specific fields are set from the system properties of the corresponding fields as specified in the comments.
# If the system properties are not set for the field, then the data is retrieved from machine agent configFile. Please refer to ControllerInfoFactory for more details.
controllerInfo:
  controllerHost: "24-6-0-saas-controller.e2e.appd-test.com"
  controllerPort: 8090
  account: "e2e-customer"
  username: "user1"
  password: "welcome"
  encryptedPassword: ""
  encryptionKey: ""
  controllerSslEnabled: false
  enableOrchestration: false
  uniqueHostId: "pramadde-aws-ec6"
  accountAccessKey: "0e6678e0-2bc0-40ad-9e8b-fa6fe440635e"
  machinePath: ""
  simEnabled: true
  applicationName: ""
  tierName: ""
  nodeName: ""